#
# Copyright (c) 2003-2017, Great Software Laboratory Pvt. Ltd. The software in this package is published under the terms of the Commercial Free Software license V.1, a copy of which has been included with this distribution in the LICENSE.md file.
#

FROM ubuntu:latest

# copy the  application to the container:
COPY runapp.sh  /

# Define working directory:
WORKDIR /

CMD  ["/bin/sh","runapp.sh"]